apiVersion: apps/v1
kind: Deployment

metadata:
  name: passin
  labels:
    app: passin

spec:
  replicas: 5

  selector:
    matchLabels:
      app: passin
  template:
    metadata:
      labels:
        app: passin
    spec:
      containers:
        - name: passin
          image: pedrodavim/nlw.service.passin:bc30ac0
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: nlw-secrets
                  key: url
            - name: BASE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: nlw-env
                  key: url
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 512Mi
          ports:
            - containerPort: 3333
